<?php
$this->title = 'Calculator';
?>

<div id="root"></div>

<?php
// Register the CSS file generated by Vite
$this->registerCssFile('@web/js/assets/index-CxqttMJe.css');

// Register the main JavaScript file generated by Vite
$this->registerJsFile('@web/js/assets/index.js', ['type' => 'module']);
?>
